dist: trusty
sudo: required
language: elixir
elixir:
  - 1.7.2
otp_release:
  - 21.0
addons:
  postgresql: '9.5'
env:
  global:
    - PGPORT=5432
    - MIX_ENV=test
    - VERBOSE_TEST=true

before_script:
  - nvm install 8.9.0
  - mix ecto.setup

script:
  - mix format --check-formatted
  - mix compile --warnings-as-errors
  - mix coveralls
  - mix credo

before_deploy:
  - cd ./assets
  - yarn install
  - ./node_modules/.bin/webpack -p
  - cd ..
  - MIX_ENV=prod mix phx.digest
  - MIX_ENV=prod mix release --env=prod

branches:
  only:
    - master
    - /^v[\d.]+/

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: P2gVtbShl6zW+4qSoEcQifLWcU85/sL12AmCMzxhoe84NS3PLt/PCmJpjT4Z5cU1zfqLetj9pCNiZOsmzOzHeFlab9lhzp+1WvOybB8C1ZLgwWncpcJQkoW6cwWcruJGjGgstg/MVjlPcPNbNbBqTWaPaJPGKVsR3RNQ9wCbLeNe3RDnuVjW55L/ZipfT1+SHI5NkD0l1A7VOEqmZ7OVpPedmuJZ2sj+hqy0XBNMHa5z7QgwvwI7d53iBJh3BYhFjuKTPmW5Dq6t+2P2/D+DyMiOSK6FDibgNIZ/5cNjMrl+riU/dD/yn859LGt6gd1ADOOUQ1XUM0BEmoHUjPe2rvDxNdeF2tzLzkIlXHJkz9lwfHDJEGRyfohZatvws8fJ97vayahF9ovrmXlN8kw/HWeZma5ShGdmMeEpAYr1WTFwEAdXM5rmRAPGFLQlbM8h9CCNVy/k1ZrtTzOOT+HyNB6GCVSA8t1/y078A9gXFEFSSrozNt8pov8TjmLjM4DsodpCSdb6ZAVUsIRJ8J3CR5qEa8AoieEHN5vZtfUKC6DKF6DWOPIzboUgTij4nBxYy6HTXlvtV3UepwpobGdCVKahr5vHLEmLixiV7OWIm6eYT7U/QiA2gdXoKpsXBe9Zn6fqCqDG0vlzDL5ATnJnwwr8WrIMbrmm1Y+0PBfp1qc=
  file_glob: true
  file: _build/prod/rel/doc_gen/releases/*/*.tar.gz
  on:
    tags: true
