dist: trusty
sudo: required
language: elixir
elixir:
  - 1.7.2
otp_release:
  - 21.0
addons:
  postgresql: '9.5'
env:
  global:
    - PGPORT=5432
    - MIX_ENV=test
    - VERBOSE_TEST=true

before_script:
  - mix ecto.setup

script:
  - mix format --check-formatted
  - mix compile --warnings-as-errors
  - mix coveralls
  - mix credo

branches:
  only:
    - master
